### ISSUE TITLE
disable title bar on firefox

### ISSUE THREAD

**Issue by gigglylo** [velitasali/GTKTitleBar#6] opened 2019-04-14 05:24 UTC
there's option in firefox to disable tittle bar, which is working great when this extension disabled. but when the extension activated. there's always title bar on firefox when not maximized, which is unwanted. so please make an exception to firefox and other similar behaviour app...

**Comment by MattSturgeon** [comment] 2019-04-21 19:44
I can reproduce this, however the extra title bar doesn't appear until un-maximising firefox.

I can launch firefox unmaximised and it has no titlebar (expected), maximise firefox and it has no titlebar (expected), however I un-maximise firefox and suddenly it has a titlebar!

<details><summary>firefox</summary>

![image](https://user-images.githubusercontent.com/5046562/56474762-320ad500-6476-11e9-8dbe-0f763d298a9a.png)

</details>

<details><summary>EDIT: this also affects chrome</summary>

![image](https://user-images.githubusercontent.com/5046562/56474784-a04f9780-6476-11e9-94de-12f8aab6ac55.png)

</details>

**Comment by MattSturgeon** [comment] 2019-04-21 21:23
Looks like `_toggleDecorationsMotif()` is enabling the titlebar whatever happens, since the `win.is_client_decorated()` check in `_handleWindow()` doesn't seem to do anything (afaict `is_client_decorated()` is always `false` and may be deprecated or broken).

A safer way would be to cache the original value and restore that instead of always enabling. This would remove the need to rely on `_handleWindow()`, or at least mitigate it not being reliable. For reference [unite](/hardpixel/unite-shell) also [caches the original motif hints](/hardpixel/unite-shell/blob/0f0ce42543ce417840f6005864ad9f2fcce2bff3/unite%40hardpixel.eu/modules/windowDecoration.js).

**Comment by MattSturgeon** [comment] 2019-04-21 22:24
Ah, this is a duplicate of hardpixel/unite-shell#93 which was fixed in hardpixel/unite-shell@5c04151c5dab5cc236ec8bf366e7f51274b8f8c3. I've ported over the changes from unite in #7.

**Closed as completed** 2019-04-24 13:56 UTC
